#spring.application.name=JournalApp
#spring.data.mongodb.port = 27017
#spring.data.mongodb.database = journalDb
#spring.data.mongodb.auto-index-creation = true
#logging.level.org.springframework.security=DEBUG
#spring.data.mongodb.password =
#spring.data.mongodb.username =

spring.application.name=JournalApp

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}

# Automatically create indexes defined in your entities/documents
spring.data.mongodb.auto-index-creation=true

# Spring Security logging
logging.level.org.springframework.security=DEBUG

server.port=${PORT:8080}